name: Tests
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: app

      - name: Run app tests
        run: pytest test_local.py
        working-directory: app

      - name: Run security tests
        run: pytest test_security.py
        working-directory: app
